name: shell commands
on:
        schedule:
                - cron: "0/5 * * * *"
        pull_request:          
jobs: 
        run-shell-commands:
           runs-on: ubuntu-latest
           steps:
                - name: linux-commands
                  run: |
                      pwd
                      ls
                - name: checkout
                  uses: actions/checkout@v2.5.0     
                - name: linux-commands-after-checkout
                  run: |
                      pwd
                      ls -a
                      echo "amar"
