name: shell commands
on:
  pull_request:
    branches:
      main          
jobs: 
        run-shell-commands:
           runs-on: ubuntu-latest
           steps:
                - name: linux-commands
                  run: |
                      pwd
                      ls
                - name: checkout
                  uses: actions/checkout@v2.5.0     
                - name: linux-commands-after-checkout
                  run: |
                      pwd
                      ls -a
                      echo "amar"
