name: shell commands
on: [push]
jobs: 
        run-shell-commands:
           runs-on: ubuntu-latest
           steps:
                - name: linux-commands
                  run: |
                      pwd
                      ls
                - name: checkout
                  uses: action/checkout@v2.5.0     
                - name: linux-commands-after-checkout
                  run: |
                      pwd
                      ls -a  
