name: shell commands
on: [push]
jobs:
  running-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: printing name
        run: echo "hello amardeep"
      - name: testing path
        run: pwd  
